../Crosswalks/bedi-esip.py -v "Concepts_Glossary" wikiGlossary/Concepts_Glossary.txt
../Crosswalks/bedi-esip.py -v "Concepts_Glossary_ISO" wikiGlossary/Concepts_Glossary_ISO.txt
../Crosswalks/bedi-esip.py -v "Concepts_Glossary_DIF" wikiGlossary/Concepts_Glossary_DIF.txt
../Crosswalks/bedi-esip.py -v "Concepts_Glossary_DIF-10" wikiGlossary/Concepts_Glossary_DIF-10.txt
../Crosswalks/bedi-esip.py -v "Concepts_Glossary_Mercury" wikiGlossary/Concepts_Glossary_Mercury.txt
../Crosswalks/bedi-esip.py -v "Concepts_Glossary_ECHO" wikiGlossary/Concepts_Glossary_ECHO.txt
../Crosswalks/bedi-esip.py -v "Concepts_Glossary_DCITE" wikiGlossary/Concepts_Glossary_DCITE.txt
../Crosswalks/bedi-esip.py -v "Concepts_Glossary_CSDGM" wikiGlossary/Concepts_Glossary_CSDGM.txt
../Crosswalks/bedi-esip.py -v "Concepts_Glossary_19110" wikiGlossary/Concepts_Glossary_19110.txt
../Crosswalks/bedi-esip.py -v "Concepts_Glossary_ACDD" wikiGlossary/Concepts_Glossary_ACDD.txt
../Crosswalks/bedi-esip.py -v "Concepts_Glossary_ADIwg" wikiGlossary/Concepts_Glossary_ADIwg.txt
../Crosswalks/bedi-esip.py -v "Concepts_Glossary_BDP" wikiGlossary/Concepts_Glossary_BDP.txt
../Crosswalks/bedi-esip.py -v "Concepts_Glossary_DCAT" wikiGlossary/Concepts_Glossary_DCAT.txt
../Crosswalks/bedi-esip.py -v "Concepts_Glossary_Dryad" wikiGlossary/Concepts_Glossary_Dryad.txt
../Crosswalks/bedi-esip.py -v "Concepts_Glossary_EML" wikiGlossary/Concepts_Glossary_EML.txt
../Crosswalks/bedi-esip.py -v "Concepts_Glossary_ECS" wikiGlossary/Concepts_Glossary_ECS.txt
../Crosswalks/bedi-esip.py -v "Concepts_Glossary_EOL" wikiGlossary/Concepts_Glossary_EOL.txt
../Crosswalks/bedi-esip.py -v "Concepts_Glossary_HCLS" wikiGlossary/Concepts_Glossary_HCLS.txt
../Crosswalks/bedi-esip.py -v "Concepts_Glossary_HDF5.1" wikiGlossary/Concepts_Glossary_HDF5.1.txt
../Crosswalks/bedi-esip.py -v "Concepts_Glossary_ISO-1" wikiGlossary/Concepts_Glossary_ISO-1.txt
../Crosswalks/bedi-esip.py -v "Concepts_Glossary_MODS" wikiGlossary/Concepts_Glossary_MODS.txt
../Crosswalks/bedi-esip.py -v "Concepts_Glossary_NUG" wikiGlossary/Concepts_Glossary_NUG.txt
../Crosswalks/bedi-esip.py -v "Concepts_Glossary_OGC-SOS" wikiGlossary/Concepts_Glossary_OGC-SOS.txt
../Crosswalks/bedi-esip.py -v "Concepts_Glossary_Onedcx" wikiGlossary/Concepts_Glossary_Onedcx.txt
../Crosswalks/bedi-esip.py -v "Concepts_Glossary_PROV" wikiGlossary/Concepts_Glossary_PROV.txt
../Crosswalks/bedi-esip.py -v "Concepts_Glossary_RDA-CISL" wikiGlossary/Concepts_Glossary_RDA-CISL.txt
../Crosswalks/bedi-esip.py -v "Concepts_Glossary_SERF" wikiGlossary/Concepts_Glossary_SERF.txt
../Crosswalks/bedi-esip.py -v "Concepts_Glossary_THREDDS" wikiGlossary/Concepts_Glossary_THREDDS.txt
../Crosswalks/bedi-esip.py -v "Concepts_Glossary_UMM" wikiGlossary/Concepts_Glossary_UMM.txt
../Crosswalks/bedi-esip.py -v "Concepts_Glossary_WSDL" wikiGlossary/Concepts_Glossary_WSDL.txt