./bedi-esip.py -v "ACDD_Variable_Attributes_Recommendations" wikiSpirals/ACDD_Usability.txt
./bedi-esip.py -v "Data_Discovery_(ACDD)" wikiSpirals/ACDD_highlyRecommended.txt
./bedi-esip.py -v "Data_Discovery_(ACDD)" wikiSpirals/ACDD_recommended.txt
./bedi-esip.py -v "Data_Discovery_(ACDD)" wikiSpirals/ACDD_suggested.txt
./bedi-esip.py -v "Data_Discovery_(CSW)" wikiSpirals/CSWAdditionalQueryables.txt
./bedi-esip.py -v "Data_Discovery_(CSW)" wikiSpirals/CSWCoreQueryables.txt
./bedi-esip.py -v "Data_Discovery_(CSW)" wikiSpirals/CSWCoreReturnables.txt
./bedi-esip.py -v "Data_Discovery_(DCAT)" wikiSpirals/DCAT_Discovery-Mandatory.txt
./bedi-esip.py -v "Data_Discovery_(DIF)" wikiSpirals/DIF_Discovery-HighlyRecommended.txt
./bedi-esip.py -v "Data_Discovery_(DIF)" wikiSpirals/DIF_Discovery-Required.txt
./bedi-esip.py -v "Data_Discovery_(DataCite)" wikiSpirals/DataCite3.1Mandatory.txt
./bedi-esip.py -v "Data_Discovery_(DataCite)" wikiSpirals/DataCite3.1Recommended.txt
./bedi-esip.py -v "Data_Discovery_(DataCite)" wikiSpirals/DataCite3.1Optional.txt
./bedi-esip.py -v "Data_Discovery_(ECHO)" wikiSpirals/ECHO_Discovery-Mandatory.txt
./bedi-esip.py -v "Data_Discovery_(ECHO)" wikiSpirals/ECHO_Discovery-Recommended.txt
./bedi-esip.py -v "Data_Discovery_(ECS)" wikiSpirals/ECS_Discovery-Recommended.txt
./bedi-esip.py -v "Data_Discovery_(FGDC)" wikiSpirals/FGDC_Discovery-Mandatory.txt
./bedi-esip.py -v "Data_Understanding_-_Mandatory_if_Applicable_(FGDC)" wikiSpirals/FGDC_Understanding.txt
./bedi-esip.py -v "Dataset_Descriptions_(W3C)" wikiSpirals/HCLS-D-R.txt
./bedi-esip.py -v "Dataset_Descriptions_(W3C)" wikiSpirals/HCLS-D-S.txt
./bedi-esip.py -v "Dataset_Descriptions_(W3C)" wikiSpirals/HCLS-D-O.txt
./bedi-esip.py -v "Dataset_Descriptions_(W3C)" wikiSpirals/HCLS-S-R.txt
./bedi-esip.py -v "Dataset_Descriptions_(W3C)" wikiSpirals/HCLS-S-S.txt
./bedi-esip.py -v "Dataset_Descriptions_(W3C)" wikiSpirals/HCLS-S-O.txt
./bedi-esip.py -v "Dataset_Descriptions_(W3C)" wikiSpirals/HCLS-V-R.txt
./bedi-esip.py -v "Dataset_Descriptions_(W3C)" wikiSpirals/HCLS-V-S.txt
./bedi-esip.py -v "Dataset_Descriptions_(W3C)" wikiSpirals/HCLS-V-O.txt
./bedi-esip.py -v "Data_Discovery_(ISO-19115-1)" wikiSpirals/ISO-1_Discovery-Conditional.txt
./bedi-esip.py -v "Data_Discovery_(ISO-19115-1)" wikiSpirals/ISO-1_Discovery-Mandatory.txt
./bedi-esip.py -v "Data_Discovery_(ISO-19115-1)" wikiSpirals/ISO-1_Discovery-Optional.txt
./bedi-esip.py -v "Data_Understanding_-_External_References_(ISO-19115-1)" wikiSpirals/ISO_ExternalRefs.txt
./bedi-esip.py -v "Data_Understanding_-_Provenance_(ISO-19115-1)" wikiSpirals/ISO_Lineage.txt
./bedi-esip.py -v "Data_Understanding_-_Quality_(ISO-19157)" wikiSpirals/ISO_Quality.txt
./bedi-esip.py -v "Service_Discovery_(ISO_19115-1)" wikiSpirals/ISO_ServiceDiscovery-Conditional.txt
./bedi-esip.py -v "Service_Discovery_(ISO_19115-1)" wikiSpirals/ISO_ServiceDiscovery-Mandatory.txt
./bedi-esip.py -v "Service_Discovery_(ISO_19115-1)" wikiSpirals/ISO_ServiceDiscovery-Optional.txt
./bedi-esip.py -v "Data_Understanding_-_User_Feedback_(ISO-19115-1)" wikiSpirals/ISO_UserFeedback.txt
./bedi-esip.py -v "Service_Discovery_(SERF)" wikiSpirals/SERF_HighlyRecommended.txt
./bedi-esip.py -v "Service_Discovery_(SERF)" wikiSpirals/SERF_Required.txt
./bedi-esip.py -v "UMM_Collection" wikiSpirals/UMM-C_HighlyRecommended.txt
./bedi-esip.py -v "UMM_Collection" wikiSpirals/UMM-C_Recommended.txt
./bedi-esip.py -v "Service_Description_(WSDL)" wikiSpirals/WSDL_Recommended.txt
#./bedi-esip.py -v "page" wikiSpirals/acquisitionDetails.txt
./bedi-esip.py -v "Documenting_Browse_Graphics" wikiSpirals/browseGraphic.txt
./bedi-esip.py -v "Documenting_Citations" wikiSpirals/citation.txt
./bedi-esip.py -v "Documenting_Resource_Content" wikiSpirals/rubricContent.txt
./bedi-esip.py -v "Supporting_Dataset_Creator_Searches" wikiSpirals/creatorSearch.txt
./bedi-esip.py -v "Documenting_Identifiers" wikiSpirals/identifiers.txt
./bedi-esip.py -v "Documenting_Distribution_Information" wikiSpirals/distributionInfo.txt
#./bedi-esip.py -v "page" wikiSpirals/entitiesAndAttributes.txt
#./bedi-esip.py -v "page" wikiSpirals/rubricDescription.txt
./bedi-esip.py -v "Documenting_Resource_Identification" wikiSpirals/rubricIdentification.txt
./bedi-esip.py -v "Documenting_Keywords" wikiSpirals/keyword.txt
./bedi-esip.py -v "Documenting_Resource_Lineage" wikiSpirals/rubricLineage.txt
./bedi-esip.py -v "Documenting_Online_Resources" wikiSpirals/OnlineResources.txt
#./bedi-esip.py -v "page" wikiSpirals/otherInformation.txt
./bedi-esip.py -v "Documenting_People_and_Organizations" wikiSpirals/people.txt
./bedi-esip.py -v "Documenting_Constraints" wikiSpirals/constraints.txt
#./bedi-esip.py -v "page" wikiSpirals/rubricExtent.txt
./bedi-esip.py -v "Documenting_Services" wikiSpirals/service.txt
./bedi-esip.py -v "Documenting_Spatial_and_Temporal_Extents" wikiSpirals/extent.txt
./bedi-esip.py -v "Documenting_Projects" wikiSpirals/ProjectContacts.txt
./bedi-esip.py -v "Documenting_Projects" wikiSpirals/ProjectDescription.txt
./bedi-esip.py -v "Documenting_Projects" wikiSpirals/ProjectExtent.txt
./bedi-esip.py -v "Documenting_Projects" wikiSpirals/ProjectIdentification.txt
./bedi-esip.py -v "Documenting_Projects" wikiSpirals/ProjectLinks.txt
