../Crosswalks/bedi-esip.py -v "ACDD_Variable_Attributes_Recommendations" wikiSpirals/ACDD_Usability.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(ACDD)" wikiSpirals/ACDD_highlyRecommended.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(ACDD)" wikiSpirals/ACDD_recommended.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(ACDD)" wikiSpirals/ACDD_suggested.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(CSW)" wikiSpirals/CSWAdditionalQueryables.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(CSW)" wikiSpirals/CSWCoreQueryables.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(CSW)" wikiSpirals/CSWCoreReturnables.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(DCAT)" wikiSpirals/DCAT_Discovery-Mandatory.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(DIF)" wikiSpirals/DIF_Discovery-HighlyRecommended.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(DIF)" wikiSpirals/DIF_Discovery-Required.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(DataCite)" wikiSpirals/DataCite3.1Mandatory.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(DataCite)" wikiSpirals/DataCite3.1Recommended.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(DataCite)" wikiSpirals/DataCite3.1Optional.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(DataCite_4.0)" wikiSpirals/DataCite_Mandatory.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(DataCite_4.0)" wikiSpirals/DataCite_Recommended.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(DataCite_4.0)" wikiSpirals/DataCite_Optional.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(ECHO)" wikiSpirals/ECHO_Discovery-Mandatory.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(ECHO)" wikiSpirals/ECHO_Discovery-Recommended.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(ECS)" wikiSpirals/ECS_Discovery-Recommended.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(FGDC)" wikiSpirals/FGDC_Mandatory.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(FGDC)" wikiSpirals/FGDC_MandatoryIfApplicable.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(FGDC)" wikiSpirals/FGDC_Optional.txt
../Crosswalks/bedi-esip.py -v "Data_Understanding_-_Mandatory_if_Applicable_(FGDC)" wikiSpirals/FGDC_Understanding.txt
../Crosswalks/bedi-esip.py -v "Dataset_Descriptions_(W3C)" wikiSpirals/HCLS-D-R.txt
../Crosswalks/bedi-esip.py -v "Dataset_Descriptions_(W3C)" wikiSpirals/HCLS-D-S.txt
../Crosswalks/bedi-esip.py -v "Dataset_Descriptions_(W3C)" wikiSpirals/HCLS-D-O.txt
../Crosswalks/bedi-esip.py -v "Dataset_Descriptions_(W3C)" wikiSpirals/HCLS-S-R.txt
../Crosswalks/bedi-esip.py -v "Dataset_Descriptions_(W3C)" wikiSpirals/HCLS-S-S.txt
../Crosswalks/bedi-esip.py -v "Dataset_Descriptions_(W3C)" wikiSpirals/HCLS-S-O.txt
../Crosswalks/bedi-esip.py -v "Dataset_Descriptions_(W3C)" wikiSpirals/HCLS-V-R.txt
../Crosswalks/bedi-esip.py -v "Dataset_Descriptions_(W3C)" wikiSpirals/HCLS-V-S.txt
../Crosswalks/bedi-esip.py -v "Dataset_Descriptions_(W3C)" wikiSpirals/HCLS-V-O.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(ISO-19115-1)" wikiSpirals/ISO-1_Discovery-Conditional.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(ISO-19115-1)" wikiSpirals/ISO-1_Discovery-Mandatory.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(ISO-19115-1)" wikiSpirals/ISO-1_Discovery-Optional.txt
../Crosswalks/bedi-esip.py -v "Data_Understanding_-_External_References_(ISO-19115-1)" wikiSpirals/ISO_ExternalRefs.txt
../Crosswalks/bedi-esip.py -v "Data_Understanding_-_Provenance_(ISO-19115-1)" wikiSpirals/ISO_Lineage.txt
../Crosswalks/bedi-esip.py -v "Data_Understanding_-_Quality_(ISO-19157)" wikiSpirals/ISO_Quality.txt
../Crosswalks/bedi-esip.py -v "Service_Discovery_(ISO_19115-1)" wikiSpirals/ISO_ServiceDiscovery-Conditional.txt
../Crosswalks/bedi-esip.py -v "Service_Discovery_(ISO_19115-1)" wikiSpirals/ISO_ServiceDiscovery-Mandatory.txt
../Crosswalks/bedi-esip.py -v "Service_Discovery_(ISO_19115-1)" wikiSpirals/ISO_ServiceDiscovery-Optional.txt
../Crosswalks/bedi-esip.py -v "Data_Understanding_-_User_Feedback_(ISO-19115-1)" wikiSpirals/ISO_UserFeedback.txt
../Crosswalks/bedi-esip.py -v "Service_Discovery_(SERF)" wikiSpirals/SERF_HighlyRecommended.txt
../Crosswalks/bedi-esip.py -v "Service_Discovery_(SERF)" wikiSpirals/SERF_Required.txt
../Crosswalks/bedi-esip.py -v "Service_Description_(WSDL)" wikiSpirals/WSDL_Recommended.txt
#../Crosswalks/bedi-esip.py -v "page" wikiSpirals/acquisitionDetails.txt
../Crosswalks/bedi-esip.py -v "Documenting_Browse_Graphics" wikiSpirals/browseGraphic.txt
../Crosswalks/bedi-esip.py -v "Documenting_Citations" wikiSpirals/citation.txt
../Crosswalks/bedi-esip.py -v "Documenting_Resource_Content" wikiSpirals/rubricContent.txt
../Crosswalks/bedi-esip.py -v "Supporting_Dataset_Creator_Searches" wikiSpirals/creatorSearch.txt
../Crosswalks/bedi-esip.py -v "Documenting_Identifiers" wikiSpirals/identifiers.txt
../Crosswalks/bedi-esip.py -v "Documenting_Distribution_Information" wikiSpirals/distributionInfo.txt
#../Crosswalks/bedi-esip.py -v "page" wikiSpirals/entitiesAndAttributes.txt
#../Crosswalks/bedi-esip.py -v "page" wikiSpirals/rubricDescription.txt
../Crosswalks/bedi-esip.py -v "Documenting_Resource_Identification" wikiSpirals/rubricIdentification.txt
../Crosswalks/bedi-esip.py -v "Documenting_Keywords" wikiSpirals/keyword.txt
../Crosswalks/bedi-esip.py -v "Documenting_Resource_Lineage" wikiSpirals/rubricLineage.txt
../Crosswalks/bedi-esip.py -v "Documenting_Online_Resources" wikiSpirals/OnlineResources.txt
#../Crosswalks/bedi-esip.py -v "page" wikiSpirals/otherInformation.txt
../Crosswalks/bedi-esip.py -v "Documenting_People_and_Organizations" wikiSpirals/people.txt
../Crosswalks/bedi-esip.py -v "Documenting_Constraints" wikiSpirals/constraints.txt
#../Crosswalks/bedi-esip.py -v "page" wikiSpirals/rubricExtent.txt
../Crosswalks/bedi-esip.py -v "Documenting_Services" wikiSpirals/service.txt
../Crosswalks/bedi-esip.py -v "Documenting_Spatial_and_Temporal_Extents" wikiSpirals/extent.txt
../Crosswalks/bedi-esip.py -v "Documenting_Projects" wikiSpirals/ProjectContacts.txt
../Crosswalks/bedi-esip.py -v "Documenting_Projects" wikiSpirals/ProjectDescription.txt
../Crosswalks/bedi-esip.py -v "Documenting_Projects" wikiSpirals/ProjectExtent.txt
../Crosswalks/bedi-esip.py -v "Documenting_Projects" wikiSpirals/ProjectIdentification.txt
../Crosswalks/bedi-esip.py -v "Documenting_Projects" wikiSpirals/ProjectLinks.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(LTER)" wikiSpirals/LTER_Identification.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(LTER)" wikiSpirals/LTER_Discovery.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(LTER)" wikiSpirals/LTER_Evaluation.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(LTER)" wikiSpirals/LTER_Access.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(LTER)" wikiSpirals/LTER_Integration.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(CMR-Granule)" wikiSpirals/CMR-Granule_Required.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(CMR-Granule)" wikiSpirals/CMR-Granule_Recommended.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(CMR-Granule)" wikiSpirals/CMR-Granule_Optional.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(CMR-Common)" wikiSpirals/CMR-Common_Required.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(CMR-Common)" wikiSpirals/CMR-Common_Recommended.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(CMR-Common)" wikiSpirals/CMR-Common_Optional.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(CMR-Collection)" wikiSpirals/CMR-Collection_Required.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(CMR-Collection)" wikiSpirals/CMR-Collection_Recommended.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(CMR-Collection)" wikiSpirals/CMR-Collection_HighlyRecommended.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(UMM-Granule)" wikiSpirals/UMM-Granule_Required.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(UMM-Granule)" wikiSpirals/UMM-Granule_Recommended.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(UMM-Granule)" wikiSpirals/UMM-Granule_Optional.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(UMM-Common)" wikiSpirals/UMM-Common_Required.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(UMM-Common)" wikiSpirals/UMM-Common_Optional.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(UMM-Collection)" wikiSpirals/UMM-Collection_Required.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(UMM-Collection)" wikiSpirals/UMM-Collection_Recommended.txt
../Crosswalks/bedi-esip.py -v "Data_Discovery_(UMM-Collection)" wikiSpirals/UMM-Collection_HighlyRecommended.txt
