./writeWikiSpiral.sh ACDD_Usability
./writeWikiSpiral.sh ACDD_highlyRecommended
./writeWikiSpiral.sh ACDD_recommended
./writeWikiSpiral.sh ACDD_suggested
./writeWikiSpiral.sh CSWAdditionalQueryables
./writeWikiSpiral.sh CSWCoreQueryables
./writeWikiSpiral.sh CSWCoreReturnables
./writeWikiSpiral.sh DCAT_Discovery-Mandatory
./writeWikiSpiral.sh DIF_Discovery-HighlyRecommended
./writeWikiSpiral.sh DIF_Discovery-Required
./writeWikiSpiral.sh DataCite3.1Mandatory
./writeWikiSpiral.sh DataCite3.1Recommended
./writeWikiSpiral.sh DataCite3.1Optional
./writeWikiSpiral.sh ECHO_Discovery-Mandatory
./writeWikiSpiral.sh ECHO_Discovery-Recommended
./writeWikiSpiral.sh ECS_Discovery-Recommended
./writeWikiSpiral.sh FGDC_Discovery-Mandatory
./writeWikiSpiral.sh FGDC_Understanding
./writeWikiSpiral.sh HCLS-D-R
./writeWikiSpiral.sh HCLS-D-S
./writeWikiSpiral.sh HCLS-D-O
./writeWikiSpiral.sh HCLS-S-R
./writeWikiSpiral.sh HCLS-S-S
./writeWikiSpiral.sh HCLS-S-O
./writeWikiSpiral.sh HCLS-V-R
./writeWikiSpiral.sh HCLS-V-S
./writeWikiSpiral.sh HCLS-V-O
./writeWikiSpiral.sh ISO-1_Discovery-Conditional
./writeWikiSpiral.sh ISO-1_Discovery-Mandatory
./writeWikiSpiral.sh ISO-1_Discovery-Optional
./writeWikiSpiral.sh ISO_ExternalRefs
./writeWikiSpiral.sh ISO_Lineage
./writeWikiSpiral.sh ISO_Quality
./writeWikiSpiral.sh ISO_ServiceDiscovery-Conditional
./writeWikiSpiral.sh ISO_ServiceDiscovery-Mandatory
./writeWikiSpiral.sh ISO_ServiceDiscovery-Optional
./writeWikiSpiral.sh ISO_UserFeedback
./writeWikiSpiral.sh SERF_HighlyRecommended
./writeWikiSpiral.sh SERF_Required
./writeWikiSpiral.sh UMM-C_HighlyRecommended
./writeWikiSpiral.sh UMM-C_Recommended
./writeWikiSpiral.sh WSDL_Recommended
./writeWikiSpiral.sh rubricAcquisition
./writeWikiSpiral.sh acquisitionDetails
./writeWikiSpiral.sh browseGraphic
./writeWikiSpiral.sh citation
./writeWikiSpiral.sh rubricContent
./writeWikiSpiral.sh creatorSearch
./writeWikiSpiral.sh identifiers
./writeWikiSpiral.sh distributionInfo
./writeWikiSpiral.sh entitiesAndAttributes
./writeWikiSpiral.sh rubricDescription
./writeWikiSpiral.sh rubricIdentification
./writeWikiSpiral.sh keyword
./writeWikiSpiral.sh rubricLineage
./writeWikiSpiral.sh OnlineResources
./writeWikiSpiral.sh otherInformation
./writeWikiSpiral.sh people
./writeWikiSpiral.sh ProjectContacts
./writeWikiSpiral.sh ProjectDescription
./writeWikiSpiral.sh ProjectExtent
./writeWikiSpiral.sh ProjectIdentification
./writeWikiSpiral.sh ProjectLinks
./writeWikiSpiral.sh constraints
./writeWikiSpiral.sh rubricExtent
./writeWikiSpiral.sh service
./writeWikiSpiral.sh extent
