./createGlossary.sh 19110
./createGlossary.sh ACDD
./createGlossary.sh ADIwg
./createGlossary.sh BDP
./createGlossary.sh CSDGM
./createGlossary.sh DCAT
./createGlossary.sh DCITE
./createGlossary.sh DIF
./createGlossary.sh DIF-10
./createGlossary.sh Dryad
./createGlossary.sh ECHO
./createGlossary.sh ECS
./createGlossary.sh EML
./createGlossary.sh EOL
./createGlossary.sh HCLS
./createGlossary.sh HDF5.1
./createGlossary.sh ISO
./createGlossary.sh ISO-1
./createGlossary.sh MODS
./createGlossary.sh Mercury
./createGlossary.sh NUG
./createGlossary.sh OGC-SOS
./createGlossary.sh Onedcx
./createGlossary.sh PROV
./createGlossary.sh RDA-CISL
./createGlossary.sh SERF
./createGlossary.sh THREDDS
./createGlossary.sh UMM
./createGlossary.sh WSDL 